### ISSUE TITLE
Hackage release?

### ISSUE THREAD

**Issue by mboes** [GaloisInc/elf-edit#1]
This library looks great. How mature is it? Time to put it up on Hackage? We'd be interested in using it in inline-java and sparkle.

Is it the case that `renderElf . parseElf == id` always?

**Comment by mboes** [comment]
To be clear, all we would need it for is to add `DT_NEEDED` entries and to edit `RPATH` / `RUNPATH`.

cc @gamazeps

**Comment by joehendrix** [comment]
If no errors are returned by parseElf, it should be nearly always be the case.  The two exceptions that I can think of are that the section header name table may be reformatted during unpacking/repacking (although I'm pretty sure we use the same algorithm as binutils), and the file some zero-length sections may be moved if they are located at an offset inside another section (binutils sometimes does this).
I'll see about getting on Hackage soon.
